//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorStandardImage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensorStandardImage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DeviceConfiguration xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; ProtocolVersion=&quot;Undefined&quot;&gt;
        ///  &lt;DeviceIdentification xmlns=&quot;urn:SNSR_STD&quot;&gt;
        ///    &lt;DeviceName&gt;CNTKRNZ150202&lt;/DeviceName&gt;
        ///    &lt;DeviceType&gt;EO Device&lt;/DeviceType&gt;
        ///    &lt;DeviceCategory&gt;Undefined&lt;/DeviceCategory&gt;
        ///  &lt;/DeviceIdentification&gt;
        ///  &lt;NotificationServiceIPAddress xmlns=&quot;urn:SNSR_STD&quot;&gt;127.0.0.1&lt;/NotificationServiceIPAddress&gt;
        ///  &lt;NotificationServic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeviceConfiguration {
            get {
                return ResourceManager.GetString("DeviceConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;DeviceStatusReport xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; ProtocolVersion=&quot;2.0&quot; ExecutionStatus=&quot;Done&quot; MessageType=&quot;Report&quot;&gt;
        ///  &lt;DeviceIdentification xmlns=&quot;urn:SNSR_STD&quot;&gt;
        ///    &lt;DeviceName&gt;CNTKRNZ150202&lt;/DeviceName&gt;
        ///    &lt;DeviceType&gt;EO Device&lt;/DeviceType&gt;
        ///    &lt;DeviceCategory&gt;Undefined&lt;/DeviceCategory&gt;
        ///  &lt;/DeviceIdentification&gt;
        ///  &lt;DetailedSensorBIT xmlns=&quot;urn:SNSR_STD&quot;&gt;
        ///    &lt;SensorIdentification&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
    }
}
